# Modules:
# - https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html
# - https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html
---
- name: === DEFAULT CONFIG FILE ===
  block:
  - name: CONFIG | Remove default configurationfile
    become: true
    ansible.builtin.file:
      path: "/etc/{{item['key']}}.d/{{item['key']}}.hcl"
      state: absent
    loop: "{{query('dict', cluster_merged)}}"
    loop_control:
      label: "Removed {{item['key']}} default config"
    when: item.value['manage_config'] and item.value['install']

- name: === CUSTOM CONFIG FILE ===
  block:
  - name: CONFIG | Manage custom configurationfile
    become: true
    ansible.builtin.copy:
      content: "{{item.value['config']|to_nice_json}}"
      dest: "/etc/{{item['key']}}.d/{{item['key']}}.json"
      owner: "root"
      group: "root"
      mode: 0644
    notify:
    - "systemd_restart_{{item['key']}}"
    loop: "{{query('dict', cluster_merged)}}"
    loop_control:
      label: "/etc/{{item['key']}}.d/{{item['key']}}.json modified"
    when: item.value['manage_config'] and item.value['install']
...
