galaxy_info:
  author: Rune Rønneseth
  description: Create files on disk from base64encoded strings (e.g. certificates)
  company: Kreditorforeninges Driftssentral DA

  license: GPL-3.0
  min_ansible_version: 2.9

  platforms:
  - name: CentOS
    versions:
    - 8
    - 7
  - name: Ubuntu
    versions:
    - 20.04
    - 18.04
    - 16.04

  galaxy_tags:
  - base64
  - files

dependencies: []
