---
- name: Converge
  hosts: all
  gather_facts: true

  tasks:

  - name: "Include roles"
    include_role:
      name: hashicluster
    vars:
      #ansible_python_interpreter: /usr/bin/python3 # yum-modules requires python v2...
      cluster:
        consul:
          install: true
          config:
            data_dir: /var/lib/consul
            server: true
            bootstrap_expect: 1
            client_addr: "0.0.0.0"
            ui: true
            performance:
              raft_multiplier: 10
            recursors:
            - 1.1.1.1
            - 8.8.8.8
            connect:
              enabled: true
            ports:
              grpc: 8502
            log_level: err
        nomad:
          install: true
          config:
            data_dir: /var/lib/nomad
            server:
              enabled: true
              bootstrap_expect: 1
      cni:
        install: true
      dns:
        forward: true
