---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos
    image: docker.io/pycontribs/centos:8
    pre_build_image: true
    privileged: true
    published_ports:
    - "0.0.0.0:4646:4646/tcp"
    - "0.0.0.0:8200:8200/tcp"
    - "0.0.0.0:8500:8500/tcp"
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../roles
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
...