---
- name: Converge
  hosts: all
  gather_facts: true

  pre_tasks:
  - name: Require python >= 2.7.9
    become: true
    ansible.builtin.package:
      name:
      - python3-minimal
      state: present

  tasks:
  - name: "Include roles"
    include_role:
      name: hashicluster
    vars:
      ansible_python_interpreter: /usr/bin/python3 # Require python >= 2.7.9
      cluster:
        consul:
          install: true
          config:
            log_level: err
            server: true
            data_dir: /var/opt/consul
            bootstrap_expect: 1
            client_addr: "0.0.0.0"
            ui: true
            performance:
              raft_multiplier: 10
            recursors:
            - 1.1.1.1
            - 8.8.8.8
            connect:
              enabled: true
            ports:
              grpc: 8502
        nomad:
          install: true
          config:
            server:
              enabled: true
              bootstrap_Expect: 1
      cni:
        install: true
      dns:
        forward: true
