# Configuration defaults.
# Override these by setting the corresponding named
# variable, without the '_' prefix
---
# HashiCorp Cluster configuration
_cluster:
  vault:
    install: false
    version: latest
    service:
      enabled: false
      masked: false
      user: root
    config: {}

  consul:
    install: false
    version: latest
    service:
      enabled: false
      masked: false
      user: root
    config: {}

  nomad:
    install: false
    version: latest
    service:
      enabled: false
      masked: false
      user: root
    config: {}
cluster_merged: "{{_cluster|combine(cluster, recursive=true)}}"

_cni:
  install: false
  version: '0.9.1'
  bin_folder: /opt/cni/bin
  template_folder: /etc/cni/net.d
  bridge_routing: false
cni_merged: "{{_cni|combine(cni, recursive=true)}}"

_dns:
  forward: false
  target_port: '8600'
dns_merged: "{{_dns|combine(dns, recursive=true)}}"
