# Configuration defaults.
# Override these by setting the corresponding named
# variable, without the '_' prefix
---
# HashiCorp Cluster applications settings
_cluster:
  vault:
    install: false
    version: latest
    service:
      enabled: false
      masked: false
      user: root
    config: {}
  consul:
    install: false
    version: latest
    service:
      enabled: false
      masked: false
      user: root
    config: {}
  nomad:
    install: false
    version: latest
    service:
      enabled: false
      masked: false
      user: root
    config: {}
cluster_merged: "{{_cluster|combine(cluster, recursive=true)}}"

# DNS forwarding via iptables
_dns:
  forward: false
  target_port: '8600'
dns_merged: "{{_dns|combine(dns, recursive=true)}}"
